# Generated by Django 5.2 on 2025-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_utilisateur_is_staff_utilisateur_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisines',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cuisines',
            name='rating',
        ),
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
