# Generated by Django 5.2 on 2025-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_cuisines_brand_remove_cuisines_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisines',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
