# Generated by Django 5.2 on 2025-05-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cuisines_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeplat',
            name='image_plat',
            field=models.ImageField(blank=True, null=True, upload_to='commande_plats/'),
        ),
        migrations.AddField(
            model_name='commandeplat',
            name='nom_plat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commandeplat',
            name='prix_plat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='commandeplat',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plat'),
        ),
        migrations.AlterField(
            model_name='commandeplat',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
        migrations.CreateModel(
            name='PlatArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plat', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats_archives/')),
                ('temp_preparation', models.CharField(blank=True, max_length=100)),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
                ('id_cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cuisines')),
            ],
        ),
    ]
